### ISSUE TITLE
Debugging installer plugin

### ISSUE THREAD

**Issue by ferben** [packagesdev/packages#16]
Hello, fortunatelly this is not an issue :)
I have two quaestions:
1) I've done installer plugin with one view but now I need to do a new version with 3 views. Is possible to do it without making 3 different plugins (any example xcodeproj will be welcome)?
2) I'll need debug installer plugin a lot, but I don^t know how to do it in Xcode 9 (I've found howto only for old Xcode at your web: http://s.sudre.free.fr/Stuff/Installer/Installer_Plugins/InstallerPlugins-Debugging.html)

Yould you help me please?
Thank you a lot.

**Comment by packagesdev** [comment]
1. It's possible but more difficult that it should be because Xcode is completely broken since version 6.4 at least when it comes to editing an Installer Plugin xib and modifying the outlets of InstallerSection and InstallerPane instances (Problem ID#35687260).

That being said, what you need to do is:

   . create an Installer Plugin project in Xcode.
   . create your 2 other InstallerPane subclasses
        . add the following temporary property:

             @property (nonatomic, retain) IBOutlet NSView *contentView;
 
   . create an InstallerSection subclass.
       . add 3 IBOutlet InstallerPane properties to this subclass (one for each pane).
       . in the didLoadMainNib method of the subclass, set the next panes of the appropriate InstallerPane properties.

   . in the xib file:

       . change the File's owner class to your InstallerSection subclass.
       . duplicate the existing InstallerPane instance twice.
       . duplicate the existing View twice.
       . set the contentView appropriately
       . connect the InstallerPane outlets of the InstallerSection subclass to the appropriate InstallerPane instances.
      . save the changes.

    . you can remove the contentView property.

And it should work.

2. In Xcode 6 and later, you need to edit the Scheme:

    In the Run Info pane:

     1. Set the Executable to be Installer.app (in /System/Library/CoreServices).
     2. Set the Launch mode to Wait for executable to be launched.
     3. Close the editor.
     4. Add a breakpoint to the title method of one of your InstallerPane subclasses. 
     5. Build your project.

   In your Packages project, add the built plugins to the Presentation steps.

   In Xcode, run the project.

   In Packages, build and run the project.

  Click Continue until you reach your plugin step. You should return to Xcode at the breaking point automatically.

I've attached a sample project.
[MultipleSectionsPlugin.zip](https://github.com/packagesdev/packages/files/1503320/MultipleSectionsPlugin.zip)

**Comment by ferben** [comment]
Thank you really much!!!
