### ISSUE TITLE
Installing to user's home directory

### ISSUE THREAD

**Issue by AegerBorder** [packagesdev/packages#45]
Hi,

first of all: thanks for this fine piece of software!

I wanted to update an Office custom templates installer (made it a year ago) and since Microsoft had decided to relocate the user templates (Office) to the user's folder (before: root Library) I was wondering how to set that path in the payload. I didn't succeed at all and so I found your article in the Q&A section. I use the latest version (1.2.5) which means I am above 1.1 which is given as the least version. I cannot find that option to install into the user's home directory although I have activated the advanced options in the preferences. What am I missing here?

Sorry for using this way but I couldn't find any other contact information on that site :)

Thanks a lot!

Patrick

**Comment by packagesdev** [comment]
There can be multiple reasons. 2 that comes im mind:

- you created a raw package project instead of a distribution project.
- you expect the payload hierarchy to start with ~. It will still start with /. Just consider it to be ~.

I would suggest to compare your Packages project document with the one attached to the Q&A. It could help figuring out where the issue lies.

**Comment by AegerBorder** [comment]
Thanks @packagesdev for your reply. I've started a whole new project now (Distribution) and there's also no option visible after enabling advanced options (see image below).

I've also tried to place the folder hierarchy at the top because you said I should consider it to start with ~. The installer then places the installation path folders in Macintosh HD/Library. I can't find out what's different from what I did a year ago. Everything went well an easy and now I don't have any idea what's going wrong.

![Image of Project and preferences](https://www.syntaxsuppe.de/patrick/preferences_project.jpg)

**Comment by packagesdev** [comment]
The Advanced Options are in the Project > Settings pane.

**Comment by AegerBorder** [comment]
The Advaned Options in the Project settings are enabled, too.
Maybe I'm just getting this all wrong. All I want is to access the User-Folder. On my machine this is:
/Users/pfr/Library/Group Containers/UBF8T346G9.Office/User Content.localized/Templates.localized

But I need to make it somewhat like this, right?
/Users/~/Library/Group Containers/UBF8T346G9.Office/User Content.localized/Templates.localized

But how? It doesn't matter if I activate the user'm home option or not... the files are always installed to

/Library/Group Containers/UBF8T346G9.Office/User Content.localized/Templates.localized 

But this is the Library under Macintosh HD and not under the user's home folder.

I just don't know why this doesn't work. A year ago this took me just a few minutes. Trying to get this working for more than a week now. Looking for the one thing I'm overseeing, I guess :/

**Comment by packagesdev** [comment]
If you followed the instructions of the Q&A, you might just be experiencing the usual issue that happens every other time where the default selected domain in Installer.app is the System domain instead of the User domain.

You can send me your package by e-mail (check http://s.sudre.free.fr/Software/Packages/resources.html feedback session) so that I can check it.
