### ISSUE TITLE
Crash after download referenced package

### ISSUE THREAD

**Issue by YotYot** [packagesdev/packages#78]
Hi, 
I'm trying to install a pkg downloaded from https (aws s3) during the installation.
The installer is not aware of the pkg size - it says 0 bytes (should it be?).
When downloading the pkg, I get to 10000% completed - and then the installer crash.

Is there any way to specify the pkg size manually? Are there logs somewhere that can help understand the crash? 

Thanks! Yotam

**Comment by singhshashi** [comment]
What is the size of the downloaded package? If that is zero bytes then it is not a package issue.

**Comment by YotYot** [comment]
The package size is about ~400Mb

**Comment by packagesdev** [comment]
The 10000% is  a known issue in Installer.app that has been there for more than a decade but, apparently, Apple does not have the resources to fix it.

You can not specify the size manually but this would not solve the issue because the percentage issue is not related to the size of the package but to the fact that someone confused KB and Bytes (there's a similar issue in the JavaScript APIs for Installer.app).

Installer.app crashing is a totally different issue that should be reported to Apple because Installer.app is an application made by Apple. Do not hold your breath for an answer or a fix though.

**Comment by packagesdev** [comment]
External issue (-> Apple).
