### ISSUE TITLE
Question - Where can the language be changed?

### ISSUE THREAD

**Issue by Lamera** [packagesdev/packages#79]
After installing the packages.pkg on macOS Catalina the whole application starts in french. I cannot see a way to change it to english.
Has anyone a solution to change it to english or german?

**Comment by ferben** [comment]
Packages.app keep macOS system settings.
If you have in SystemPreferences→Language&Region French as 1st place Packages.app will run in French.
Simple place English to 1st place in these preference pane and Packages app will be in English.

Otherwise if you have macOS 10.15 Catalina see https://beebom.com/how-customize-language-settings-specific-apps-macos-catalina/
