### ISSUE TITLE
High Sierra Goldin Issue

### ISSUE THREAD

**Issue by VishwasShashidhar** [packagesdev/packages#9]
On High Sierra, we are facing a `goldin` issue which is throwing a "Not enough memory to perform this operation" error.

Anyone else facing the same issue?

```
==============================================================================
ERROR:

Description:

goldin_64 returned error code '254'
Description:

Not enough memory to perform operation.
==============================================================================

```

**Comment by jcrate** [comment]
The fix is as simple as changing line 1055 in goldin main.c to:
`if (strcmp(tStatFileSystem.f_fstypename,"hfs")!=0 && strcmp(tStatFileSystem.f_fstypename,"apfs")!=0)`

You can clone the goldin project, use Xcode to make the change, build, archive, then rename goldin to goldin_64 and replace the old executable in /usr/local/bin and it will function on macOS 10.13.

**Comment by VishwasShashidhar** [comment]
Awesome @jcrate! That fixed it. Thank you.

Should I create a PR and get this merged @packagesdev ?

**Comment by ferben** [comment]
Have you ever try latest [beta](http://s.sudre.free.fr/Software/Packages/Q&A_6.html)?

**Comment by VishwasShashidhar** [comment]
You are right, the issue seems to be solved with the beta. Thanks @ferben
