### ISSUE TITLE
Trying to copy a file from Additional resources fails

### ISSUE THREAD

**Issue by integral-llc** [packagesdev/packages#90]
I do have some assisting files for the application to run 
![image](https://user-images.githubusercontent.com/1841073/113066461-2eaf1680-9180-11eb-9db1-cd6d96902f06.png)
which I need to copy to a certain location. 
To just test it, I'm trying to copy them into the current user's Downloads folder.

The content of my post-install script is 
```
cp "$DSTROOT/XcodeSystemResources.pkg" "$HOME/Downloads"
exit 0
```

However the installer ends with an error message.

P.S. are there any logs so I can check what errors are happening during the execution of post-installs scripts?

**Comment by TheTechRobo** [comment]
does adding full disk access solve it ?

**Comment by integral-llc** [comment]
I don't see anything under project settings about disc access. Where do I do this?

![image](https://user-images.githubusercontent.com/1841073/113083181-582c6a00-91a1-11eb-9582-9cc98e7a0e97.png)

**Comment by TheTechRobo** [comment]
Nevermind, I dont think that full disk access would help anyway.

**Comment by packagesdev** [comment]
The issue is that the additional resources are not installed. They are just extracted in a temporary folder during the installation (and they will be removed at the end of the installation).

To access the additional resources from a pre- or post-installation script, you just need to reference the ./ folder (i.e. the current folder for your script).

So the script should look more like this:

```
#!/bin/sh

/bin/cp "./XcodeSystemResources.pkg" "$HOME/Downloads"

exit 0
```

**Comment by integral-llc** [comment]
thank you, that's what I exactly did and all worked as needed. But good to have a confirmation :)
